server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=userServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/fallback/user-service

# Notification Service
spring.cloud.gateway.server.webflux.routes[1].id=notification-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=notificationServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback/notification-service

# Resilience4j
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=2

resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.notificationServiceCircuitBreaker.permitted-number-of-calls-in-half-open-state=2

logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG