server.port=8081

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.hostname=notification-service
eureka.instance.prefer-ip-address=false

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.properties.spring.json.trusted.packages=ru.aston.notificationservice.kafka
spring.kafka.consumer.properties.spring.json.value.default.type=ru.aston.notificationservice.kafka.UserEvent

app.kafka.user-events-topic=user-events

spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
